# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jg9rAT6O7lzJTqIjbdN5jJ33_EZFmApo
"""

# Problem 1

def calculate_hra(basic_salary):
    return basic_salary * 0.20

def calculate_da(basic_salary):
    return basic_salary * 0.10

def calculate_net_salary(basic_salary):
    hra = calculate_hra(basic_salary)
    da = calculate_da(basic_salary)
    net_salary = basic_salary + hra + da
    return hra, da, net_salary

employee_name = input("Enter Employee Name: ")
basic_salary = float(input("Enter Basic Salary: "))

hra, da, net_salary = calculate_net_salary(basic_salary)

print("\n------ Employee Salary Details ------")
print("Employee Name :", employee_name)
print("Basic Salary  :", basic_salary)
print("HRA (20%)     :", hra)
print("DA (10%)      :", da)
print("Net Salary    :", net_salary)

# Problem 2

def calculate_total(marks):
    return sum(marks)

def calculate_percentage(total, num_subjects):
    return total / num_subjects

def assign_grade(percentage):
    if percentage >= 90:
        return "A"
    elif percentage >= 75:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 40:
        return "D"
    else:
        return "F"

marks = []

print("Enter marks for 5 subjects:")

for i in range(5):
    mark = float(input(f"Subject {i+1}: "))
    marks.append(mark)

total = calculate_total(marks)
percentage = calculate_percentage(total, len(marks))
grade = assign_grade(percentage)
print("\n------ Student Result ------")
print("Total Marks :", total)
print("Percentage  :", percentage, "%")
print("Grade       :", grade)

# Problem 3

grade_criteria = (
    "A: 90% and above",
    "B: 75% - 89%",
    "C: 60% - 74%",
    "D: 40% - 59%",
    "F: Below 40%"
)

def calculate_total(marks):
    return sum(marks)

def calculate_percentage(total):
    return total / 5

def assign_grade(percentage):
    if percentage >= 90:
        return "A"
    elif percentage >= 75:
        return "B"
    elif percentage >= 60:
        return "C"
    elif percentage >= 40:
        return "D"
    else:
        return "F"

def display_student(student):
    print("--------------------------------------")
    print("Roll No     :", student["Roll No"])
    print("Name        :", student["Name"])
    print("Marks       :", student["Marks"])
    print("Total Marks :", student["Total"])
    print("Percentage  :", student["Percentage"], "%")
    print("Grade       :", student["Grade"])


students = []

num_students = int(input("Enter number of students: "))

for i in range(num_students):
    print(f"\nEnter details of Student {i+1}")

    roll = input("Enter Roll No: ")
    name = input("Enter Name: ")

    marks = []
    print("Enter marks of 5 subjects:")
    for j in range(5):
        mark = float(input(f"Subject {j+1}: "))
        marks.append(mark)

    total = calculate_total(marks)
    percentage = calculate_percentage(total)
    grade = assign_grade(percentage)

    student = {
        "Roll No": roll,
        "Name": name,
        "Marks": marks,
        "Total": total,
        "Percentage": percentage,
        "Grade": grade
    }

    students.append(student)

print("\nGrade Criteria:")
for criteria in grade_criteria:
    print(criteria)

print("\n========== Student Records ==========")
for student in students:
    display_student(student)

topper = students[0]

for student in students:
    if student["Percentage"] > topper["Percentage"]:
        topper = student

print("\n========== Topper ==========")
print("Name       :", topper["Name"])
print("Roll No    :", topper["Roll No"])
print("Percentage :", topper["Percentage"], "%")
print("Grade      :", topper["Grade"])

