# -*- coding: utf-8 -*-
"""assignment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIv5DH4omtIuXOzQagFN_8RW28xSwHlZ
"""

# Problem 1

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

df = pd.read_csv("/content/StudentsPerformance.csv")

print(df.head())

print("\nMissing Values:")
print(df.isnull().sum())

df = df.dropna()

marks = df["math score"]

print("\nMean Math Score:", np.mean(marks))
print("Median Math Score:", np.median(marks))
print("Standard Deviation:", np.std(marks))

plt.figure(figsize=(6,4))
plt.hist(marks, bins=10, edgecolor="black")
plt.title("Histogram of Math Scores")
plt.xlabel("Math Score")
plt.ylabel("Frequency")
plt.show()

plt.figure(figsize=(6,4))
plt.scatter(df["reading score"], df["math score"])
plt.title("Reading Score vs Math Score")
plt.xlabel("Reading Score")
plt.ylabel("Math Score")
plt.show()

X = df[["reading score"]]
y = df["math score"]

model = LinearRegression()
model.fit(X, y)

predicted = model.predict(X)

plt.figure(figsize=(6,4))
plt.scatter(df["reading score"], y, label="Actual Data")
plt.plot(df["reading score"], predicted, color="red", linewidth=2, label="Regression Line")
plt.title("Linear Regression: Reading Score vs Math Score")
plt.xlabel("Reading Score")
plt.ylabel("Math Score")
plt.legend()
plt.show()

df["Predicted Math Score"] = predicted

print("\nPredicted Values:")
print(df[["reading score", "math score", "Predicted Math Score"]].head(10))









