# -*- coding: utf-8 -*-
"""assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R26d38oRvY3ErbAZF2ZIFcplSakLfUH4
"""

# Problem 1

import pandas as pd
import numpy as np

data = {
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Printer"],
    "Price": [55000, 800, 1500, 12000, 8500]
}

df = pd.DataFrame(data)

df.to_csv("products.csv", index=False)

print("CSV file created successfully.\n")

products = pd.read_csv("products.csv")

print("Product Details:")
print(products)

average_price = np.mean(products["Price"])

print("\nAverage Price:", average_price)

def above_average_products(df, avg):
    print("\nProducts Priced Above Average:")

    for index, row in df.iterrows():
        if row["Price"] > avg:
            print(row["Product"], "-", row["Price"])

above_average_products(products, average_price)

# Problem 2

import pandas as pd
import numpy as np

data = {
    "Day": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    "Temperature": [18, 24, 31, 29, 35, 19, 27]
}

df = pd.DataFrame(data)

df.to_csv("temperature.csv", index=False)

print("CSV file created successfully.\n")

temperature_data = pd.read_csv("temperature.csv")

print("Temperature Data:")
print(temperature_data)

highest = np.max(temperature_data["Temperature"])
lowest = np.min(temperature_data["Temperature"])
average = np.mean(temperature_data["Temperature"])

print("\nHighest Temperature :", highest, "°C")
print("Lowest Temperature  :", lowest, "°C")
print("Average Temperature :", average, "°C")

def classify_temperature(temp):
    if temp < 20:
        return "Cold"
    elif temp <= 30:
        return "Moderate"
    else:
        return "Hot"

print("\nTemperature Categories:")
for index, row in temperature_data.iterrows():
    category = classify_temperature(row["Temperature"])
    print(row["Day"], ":", row["Temperature"], "°C -", category)